### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ghost** [yjkony/atom-animated-cursor#1]
[Enter steps to reproduce below:]
1. Open a new empty tab with Ctrl+N
2. Disable animated-cursor
3. Switch empty tab
4. Switch back to settings tab
5. Enable animated-cursor
6. Switch to empty tab
7. Switch back to settings tab
8. Change 'Animation Direction' to 'horizontal'
9. Error appeared after that

**Atom Version**: 1.0.2
**System**: Ubuntu 15.04
**Thrown From**: [animated-cursor](https://github.com/yjkony/atom-animated-cursor) package, v1.0.5
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/szymon/.atom/packages/animated-cursor/lib/animated-cursor.coffee:39

TypeError: undefined is not a function
  at module.exports.AnimatedCursor.updateDirection (/home/szymon/.atom/packages/animated-cursor/lib/animated-cursor.coffee:39:17)
  at /usr/share/atom/resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:233:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:190:28)
  at HTMLSelectElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:204:26)
  at HTMLSelectElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLSelectElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -8:46.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -8:43.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -7:03.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:59.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:20.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  3x -6:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.2.0 application:new-file (button.btn.icon.enablement.icon-playback-play)
```
### Config

``` json
{
  "core": {},
  "animated-cursor": {
    "animationDirection": "horizontal"
  }
}
```
### Installed Packages

``` coffee
# User
animated-cursor, v1.0.5
auto-indent, v0.5.0
file-icons, v1.5.8
hex, v0.6.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-x86asm, v0.5.1
linter-cpplint, v0.1.4
minimap, v4.11.2
minimap-color-highlight, v4.1.4
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
tab-control, v0.6.7
terminal-panel, v1.14.1
tree-ignore, v0.2.6
tree-view-breadcrumb, v0.6.1
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.1.1
white-cursor, v0.6.0
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by yjkony** [comment]
@RebornMarauder, thanks you for reporting.
I'll debug it. Please wait for fix it.
